import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Allocation, Exercise, Member } from "./domain";
import { reportText } from "./domain";

type PdfData = { members: Member[]; exercises: Exercise[]; allocations: Allocation[]; files: File[] };
const letter: [number, number] = [612, 792];
function text(page: ReturnType<PDFDocument["addPage"]>, value: string, x: number, y: number, size = 10, bold = false, fonts?: { regular: Awaited<ReturnType<PDFDocument["embedFont"]>>; bold: Awaited<ReturnType<PDFDocument["embedFont"]>> }) {
  page.drawText(value, { x, y, size, font: bold ? fonts?.bold : fonts?.regular, color: rgb(.08, .11, .1), maxWidth: 500 });
}
export async function createAssignmentPdf(data: PdfData) {
  const doc = await PDFDocument.create(); const regular = await doc.embedFont(StandardFonts.Helvetica); const bold = await doc.embedFont(StandardFonts.HelveticaBold); const fonts = { regular, bold };
  let p = doc.addPage(letter); text(p, "UNIVERSIDAD MARIANO GÁLVEZ DE GUATEMALA", 116, 710, 14, true, fonts); text(p, "FACULTAD DE INGENIERÍA EN SISTEMAS", 160, 690, 11, true, fonts); text(p, "SEDE: Campus Villa Nueva", 74, 640, 11, true, fonts); text(p, "JORNADA: Vespertina", 74, 618, 11, true, fonts); text(p, "CARRERA: Ingeniería en Sistemas", 74, 596, 11, true, fonts); text(p, "CURSO: Matemática Discreta", 74, 574, 11, true, fonts); text(p, "Reporte de desempeño semanal", 205, 515, 13, true, fonts); text(p, "INTEGRANTES DEL GRUPO:", 74, 470, 11, true, fonts); data.members.forEach((m, i) => { text(p, `•  ${m.name}`, 90, 444 - i * 22, 10, false, fonts); text(p, `CARNÉ: ${m.carnet}`, 350, 444 - i * 22, 10, true, fonts); }); text(p, "Semana del 03/08/2026 al 09/08/2026", 330, 72, 9, false, fonts);
  p = doc.addPage(letter); text(p, "DESEMPEÑO GRUPAL", 230, 724, 14, true, fonts); text(p, "Semana #5 de trabajo", 72, 690, 11, false, fonts); const report = reportText([...new Set(data.exercises.map((e) => e.section))], 0, 0, []); const words = report.split(" "); let line = "", y = 658; for (const word of words) { if ((line + word).length > 92) { text(p, line, 72, y, 10, false, fonts); y -= 17; line = ""; } line += word + " "; } text(p, line, 72, y, 10, false, fonts); y -= 45; p.drawRectangle({ x: 60, y: y - 24, width: 492, height: 24, color: rgb(.55, .82, .29) }); text(p, "INTEGRANTE", 68, y - 16, 8, true, fonts); text(p, "CARNÉ", 280, y - 16, 8, true, fonts); text(p, "TOTAL (100)", 460, y - 16, 8, true, fonts); data.members.forEach((m, i) => { text(p, m.name, 68, y - 39 - i * 25, 8, false, fonts); text(p, m.carnet, 280, y - 39 - i * 25, 8, false, fonts); text(p, "100", 490, y - 39 - i * 25, 10, false, fonts); });
  p = doc.addPage(letter); text(p, "GRUPO     2", 452, 720, 11, false, fonts); p.drawRectangle({ x: 32, y: 650, width: 548, height: 40, borderWidth: 1 }); text(p, "MATEMÁTICA", 220, 660, 24, true, fonts); text(p, "CICLO: 2", 42, 625, 10, false, fonts); text(p, "SECCIÓN: A", 42, 603, 10, false, fonts); text(p, "SEMESTRE: 2", 42, 581, 10, false, fonts); text(p, "UNIVERSIDAD", 235, 480, 27, false, fonts); text(p, "MARIANO GÁLVEZ", 215, 444, 27, false, fonts); p.drawRectangle({ x: 32, y: 300, width: 548, height: 68, borderWidth: 1 }); text(p, "TAREA No. 5", 242, 340, 17, false, fonts); text(p, "TEMA: Ejercicios semanales", 175, 314, 15, false, fonts); ["CARÁTULA                 5", "FECHA DE ENTREGA   5", "PRESENTACIÓN         10", "EJERCICIOS COMPLETOS 40", "EJERCICIOS AL AZAR(3) 40", "TOTAL                         100"].forEach((v, i) => text(p, v, 52, 270 - i * 24, 11, i === 5, fonts));
  p = doc.addPage(letter); text(p, "INTEGRANTES DEL GRUPO:", 66, 706, 15, true, fonts); data.members.forEach((m, i) => { text(p, `•  ${m.name}`, 86, 672 - i * 27, 12, false, fonts); text(p, `CARNÉ: ${m.carnet}`, 360, 672 - i * 27, 11, true, fonts); });
  for (const file of data.files) { const bytes = await file.arrayBuffer(); if (file.type === "application/pdf") { const source = await PDFDocument.load(bytes); (await doc.copyPages(source, source.getPageIndices())).forEach((page) => doc.addPage(page)); } else { const img = file.type === "image/png" ? await doc.embedPng(bytes) : await doc.embedJpg(bytes); const page = doc.addPage(letter); const scale = Math.min(540 / img.width, 720 / img.height); page.drawImage(img, { x: (612 - img.width * scale) / 2, y: (792 - img.height * scale) / 2, width: img.width * scale, height: img.height * scale }); } }
  const pages = doc.getPages(); pages.forEach((page, i) => text(page, `${i + 1}`, 300, 24, 8, false, fonts)); return doc.save();
}
