"use client";
import { useMemo, useState } from "react";
import { BookOpen, CheckCircle2, ClipboardCheck, FileDown, FileText, LayoutDashboard, Menu, Plus, Send, Settings, Upload, Users, X } from "lucide-react";
import { buildExercises, demoMembers, distribute, generateLabels, type Allocation, type Exercise } from "@/lib/domain";
import { createAssignmentPdf } from "@/lib/pdf";

type View = "Resumen" | "Cursos" | "Integrantes" | "Tareas" | "Distribución" | "Entregas" | "Evaluación" | "PDF final" | "Configuración";
const nav: [View, typeof LayoutDashboard][] = [["Resumen",LayoutDashboard],["Cursos",BookOpen],["Integrantes",Users],["Tareas",FileText],["Distribución",Send],["Entregas",Upload],["Evaluación",ClipboardCheck],["PDF final",FileDown],["Configuración",Settings]];
const sections = [{ id:"s53",name:"Sección 5.3",labels:["5","10","15","20","25"]},{id:"s54",name:"Sección 5.4",labels:["5","10","15","20","25"]},{id:"s55",name:"Sección 5.5",labels:["5","10","15","20","25"]}];

export default function AppShell() {
 const members=demoMembers; const [view,setView]=useState<View>("Resumen"); const [menu,setMenu]=useState(false); const [exercises,setExercises]=useState<Exercise[]>(()=>buildExercises(sections)); const [allocations,setAllocations]=useState<Allocation[]>(()=>distribute(buildExercises(sections),members)); const [rule,setRule]=useState<"manual"|"range"|"odd"|"even"|"multiple">("multiple"); const [input,setInput]=useState("5 al 25"); const [files,setFiles]=useState<File[]>([]); const [toast,setToast]=useState("");
 const totals=useMemo(()=>members.map(m=>({m,count:allocations.filter(a=>a.memberId===m.id).length})),[allocations,members]);
 const go=(v:View)=>{setView(v);setMenu(false)}; const notify=(v:string)=>{setToast(v);setTimeout(()=>setToast(""),2800)};
 const regenerate=()=>{try{const labels=generateLabels(input,rule); const next=buildExercises(sections.map(s=>({...s,labels}))); setExercises(next);setAllocations(distribute(next,members));notify(`${next.length} ejercicios distribuidos sin duplicados`)}catch(e){notify(e instanceof Error?e.message:"No se pudo distribuir")}};
 const download=async()=>{notify("Generando documento…");const bytes=await createAssignmentPdf({members,exercises,allocations,files});const blob=new Blob([bytes as BlobPart],{type:"application/pdf"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="tarea-semana-5.pdf";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify("PDF final generado correctamente")};
 return <div className="app"><aside className={menu?"sidebar open":"sidebar"}><div className="brand"><span>CT</span><div>Coordinador<br/><small>de Tareas</small></div><button className="close" onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([label,Icon])=><button key={label} className={view===label?"active":""} onClick={()=>go(label)}><Icon size={18}/>{label}</button>)}</nav><div className="profile"><div>CD</div><span>Carlos Díaz<small>Coordinador</small></span></div></aside>{menu&&<button className="scrim" aria-label="Cerrar menú" onClick={()=>setMenu(false)}/>}<main><header><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu/></button><div><span>Matemática Discreta</span><small>Tarea 5 · Semana 5</small></div><button className="outline" onClick={()=>go("Configuración")}><Settings size={16}/> Configurar</button></header><section className="content">{view==="Resumen"&&<Dashboard go={go}/>} {view==="Cursos"&&<Courses/>} {view==="Integrantes"&&<Members totals={totals}/>} {view==="Tareas"&&<Tasks/>} {view==="Distribución"&&<Distribution members={members} exercises={exercises} allocations={allocations} setAllocations={setAllocations} rule={rule} setRule={setRule} input={input} setInput={setInput} regenerate={regenerate}/>} {view==="Entregas"&&<Submissions files={files} setFiles={setFiles}/>} {view==="Evaluación"&&<Evaluation/>} {view==="PDF final"&&<PdfBuilder files={files} download={download}/>} {view==="Configuración"&&<SettingsView/>}</section></main>{toast&&<div className="toast"><CheckCircle2 size={18}/>{toast}</div>}</div>;
}
function Title({eyebrow,title,children}:{eyebrow:string,title:string,children?:React.ReactNode}){return <div className="title"><div><small>{eyebrow}</small><h1>{title}</h1></div>{children}</div>}
function Dashboard({go}:{go:(v:View)=>void}){return <><Title eyebrow="Sábado, 1 de agosto" title="Buenas tardes, Carlos"/><div className="hero"><div><span className="pill">TAREA EN CURSO</span><h2>Matemática Discreta · Tarea 5</h2><p>Semana del 03/08/2026 al 09/08/2026</p><div className="progress"><i style={{width:"67%"}}/></div><small>4 de 6 entregas recibidas</small></div><button onClick={()=>go("Entregas")}>Gestionar entregas →</button></div><div className="stats"><article><span>Cursos activos</span><strong>3</strong><small>Periodo 2026</small></article><article><span>Próximas tareas</span><strong>2</strong><small>En los próximos 7 días</small></article><article><span>Entregas pendientes</span><strong className="amber">2</strong><small>Vencen mañana</small></article><article><span>Listas para compilar</span><strong className="green">1</strong><small>Todo revisado</small></article></div><div className="panel"><div className="panel-head"><div><h3>Progreso de la tarea</h3><p>Completa cada etapa para generar el documento final.</p></div></div><div className="steps">{[["1","Ejercicios definidos","15 ejercicios en 3 secciones",true],["2","Distribución completada","Carga equilibrada entre 6 integrantes",true],["3","Recibir entregas","4 de 6 archivos recibidos",false],["4","Evaluar integrantes","Pendiente de revisión",false],["5","Generar PDF final","Listo cuando completes la evaluación",false]].map(([n,t,d,done])=><button key={String(n)} onClick={()=>go(n==="3"?"Entregas":n==="4"?"Evaluación":n==="5"?"PDF final":"Distribución")}><b className={done?"done":""}>{done?<CheckCircle2 size={17}/>:n}</b><span><strong>{t}</strong><small>{d}</small></span><em>›</em></button>)}</div></div></>}
function Courses(){return <><Title eyebrow="Organización" title="Cursos"><button className="primary"><Plus size={17}/> Nuevo curso</button></Title><div className="cards">{["Matemática Discreta","Física I","Programación II"].map((c,i)=><article className="course" key={c}><span>{["MD","F1","P2"][i]}</span><small>{i?"EN PREPARACIÓN":"ACTIVO"}</small><h3>{c}</h3><p>Sección A · Grupo {i+1}</p><footer><b>{[6,5,4][i]} integrantes</b><button>Ver curso →</button></footer></article>)}</div></>}
function Members({totals}:{totals:{m:(typeof demoMembers)[number];count:number}[]}){return <><Title eyebrow="Matemática Discreta" title="Integrantes del grupo"><button className="primary"><Plus size={17}/> Agregar integrante</button></Title><div className="panel table-wrap"><table><thead><tr><th>Integrante</th><th>Carné</th><th>Asignados esta semana</th><th>Saldo histórico</th><th>Estado</th></tr></thead><tbody>{totals.map(({m,count})=><tr key={m.id}><td><b>{m.name}</b><small>{m.shortName}</small></td><td>{m.carnet}</td><td>{count} ejercicios</td><td><span className="balance">{m.historicalLoad}</span></td><td><span className="status">Activo</span></td></tr>)}</tbody></table></div></>}
function Tasks(){return <><Title eyebrow="Planificación" title="Tareas semanales"><button className="primary"><Plus size={17}/> Nueva tarea</button></Title><div className="panel"><div className="task-row"><div className="task-num">05</div><div><span className="status">RECIBIENDO ENTREGAS</span><h3>Tarea 5 · Sucesiones y series</h3><p>3 secciones · 15 ejercicios · Fecha límite 09/08/2026 23:59</p></div><button className="outline">Abrir tarea</button></div><div className="task-row muted"><div className="task-num">04</div><div><span className="status gray">FINALIZADA</span><h3>Tarea 4 · Relaciones de recurrencia</h3><p>PDF final generado · 31 páginas</p></div><button className="outline">Ver historial</button></div></div></>}
function Distribution({members,exercises,allocations,setAllocations,rule,setRule,input,setInput,regenerate}:{members:typeof demoMembers;exercises:Exercise[];allocations:Allocation[];setAllocations:React.Dispatch<React.SetStateAction<Allocation[]>>;rule:"manual"|"range"|"odd"|"even"|"multiple";setRule:(v:"manual"|"range"|"odd"|"even"|"multiple")=>void;input:string;setInput:(v:string)=>void;regenerate:()=>void}){const move=(eid:string,mid:string)=>setAllocations(a=>a.map(x=>x.exerciseId===eid?{...x,memberId:mid}:x));return <><Title eyebrow="Tarea 5 · Modo híbrido recomendado" title="Distribución de ejercicios"><button className="primary" onClick={regenerate}>Redistribuir</button></Title><div className="generator panel"><label>Regla de selección<select value={rule} onChange={e=>setRule(e.target.value as typeof rule)}><option value="range">Rango completo</option><option value="odd">Impares</option><option value="even">Pares</option><option value="multiple">Múltiplos de 5</option><option value="manual">Lista manual</option></select></label><label>Valores<input value={input} onChange={e=>setInput(e.target.value)} placeholder="1 al 25 o 5, 10, 15"/></label><div><small>Vista previa</small><b>{generateSafe(input,rule).join(", ")||"—"}</b></div></div><div className="matrix panel"><table><thead><tr><th>Integrante</th>{[...new Set(exercises.map(e=>e.section))].map(s=><th key={s}>{s}</th>)}<th>Total</th></tr></thead><tbody>{members.map(m=><tr key={m.id}><td><b>{m.shortName}</b><small>Histórico: {m.historicalLoad}</small></td>{[...new Set(exercises.map(e=>e.section))].map(s=><td key={s}>{exercises.filter(e=>e.section===s&&allocations.find(a=>a.exerciseId===e.id)?.memberId===m.id).map(e=><select aria-label={`Asignación ${s} ${e.label}`} key={e.id} value={m.id} onChange={x=>move(e.id,x.target.value)}><option value={m.id}>{e.label}</option>{members.filter(o=>o.id!==m.id).map(o=><option key={o.id} value={o.id}>{e.label} → {o.shortName}</option>)}</select>)}</td>)}<td><strong>{allocations.filter(a=>a.memberId===m.id).length}</strong></td></tr>)}</tbody></table></div><div className="notice"><CheckCircle2/> Cobertura completa: {exercises.length} asignados · 0 duplicados · 0 pendientes · semilla 5</div></>}
function generateSafe(input:string,rule:"manual"|"range"|"odd"|"even"|"multiple"){try{return generateLabels(input,rule)}catch{return []}}
function Submissions({files,setFiles}:{files:File[];setFiles:React.Dispatch<React.SetStateAction<File[]>>}){return <><Title eyebrow="Tarea 5" title="Recepción de entregas"><span className="pill neutral">{files.length} archivo(s) cargado(s)</span></Title><label className="drop"><Upload size={32}/><strong>Arrastra PDFs o imágenes aquí</strong><span>PDF, JPG, PNG o WEBP · máximo 25 MB por archivo</span><input type="file" multiple accept="application/pdf,image/png,image/jpeg,image/webp" onChange={e=>setFiles(f=>[...f,...Array.from(e.target.files||[])])}/><b>Seleccionar archivos</b></label><div className="panel file-list">{files.length===0?<div className="empty"><FileText/><h3>Aún no hay archivos</h3><p>Los archivos se guardan localmente en esta demostración y se incorporan al PDF final.</p></div>:files.map((f,i)=><div key={`${f.name}-${i}`}><FileText/><span><b>{f.name}</b><small>{(f.size/1024/1024).toFixed(2)} MB · Listo para compilar</small></span><button onClick={()=>setFiles(x=>x.filter((_,n)=>n!==i))}>Eliminar</button></div>)}</div></>}
function Evaluation(){const criteria=["Puntualidad","Presentación PDF","Trabajo en equipo","Comunicación","Ejercicios completos"];return <><Title eyebrow="Revisión rápida" title="Evaluación del grupo"><button className="primary">Guardar evaluaciones</button></Title><div className="panel table-wrap"><table><thead><tr><th>Integrante</th>{criteria.map(c=><th key={c}>{c}<small>Máx. 20</small></th>)}<th>Total</th></tr></thead><tbody>{demoMembers.map(m=><tr key={m.id}><td><b>{m.shortName}</b><small>{m.carnet}</small></td>{criteria.map(c=><td key={c}><input className="score" type="number" min="0" max="20" defaultValue="20"/></td>)}<td><strong>100</strong></td></tr>)}</tbody></table></div><p className="notice"><CheckCircle2/> La suma máxima de los criterios es 100 puntos.</p></>}
function PdfBuilder({files,download}:{files:File[];download:()=>void}){const blocks=["Portada del reporte","Desempeño grupal y tablas","Carátula oficial","Integrantes del grupo",...files.map(f=>f.name)];return <><Title eyebrow="Constructor final" title="Compilar PDF"><button className="primary" onClick={download}><FileDown size={17}/> Generar y descargar</button></Title><div className="builder"><div className="panel"><h3>Orden de páginas</h3><p>Arrastra los bloques para ajustar el documento.</p>{blocks.map((b,i)=><div className="block" key={`${b}-${i}`}><b>⋮⋮</b><span><strong>{b}</strong><small>{i<4?"Página administrativa generada":"Entrega recibida"}</small></span><em>{i+1}</em></div>)}</div><div className="preview panel"><div className="paper"><small>UNIVERSIDAD MARIANO GÁLVEZ</small><h2>Reporte de desempeño semanal</h2><p>Matemática Discreta</p><hr/><b>INTEGRANTES DEL GRUPO</b>{demoMembers.map(m=><span key={m.id}>• {m.name}</span>)}</div><small>{4+files.length} páginas estimadas · Carta · Calidad alta</small></div></div></>}
function SettingsView(){return <><Title eyebrow="Preferencias" title="Configuración"/><div className="panel form"><h3>Identidad del sistema</h3><label>Nombre de la aplicación<input defaultValue="Coordinador de Tareas"/></label><div className="two"><label>País<select defaultValue="GT"><option value="GT">Guatemala</option></select></label><label>Zona horaria<select defaultValue="America/Guatemala"><option>America/Guatemala</option></select></label></div><h3>Documento predeterminado</h3><div className="two"><label>Tamaño<select defaultValue="letter"><option value="letter">Carta (8.5 × 11 in)</option></select></label><label>Idioma<select defaultValue="es"><option value="es">Español</option></select></label></div><button className="primary">Guardar cambios</button></div></>}
